### ISSUE TITLE
Clarify the licensing situation for metadata extracted from udev rules

### ISSUE THREAD

**Issue by nbraud** [Yubico/libu2f-host#113]
In the Debian package, I [generate Appstream metadata] by parsing the udev rules, so that Appstream can inform users they should install `libu2f-udev` for their device to be supported (note that `libu2f-udev` is pulled in by `task-desktop` and U2F-capable applications, so it should be installed in the vast majority of cases).

Upstream is [unhappy] with my decision to mark the generated-metadata as LGPL-licensed (though it's unclear whether a set of USB vendor and device ids is copyrightable at all), so I'm forwarding this issue here to check whether it would be possible to have the udev rules be more-liberally licensed, or clarify whether the generated metadata must be under LGPL.

Note that I can relicense the metadata-generation scripts if necessary.

[generate Appstream metadata]: https://salsa.debian.org/auth-team/libu2f-host/blob/master/debian/libu2f-udev.metainfo.py
[unhappy]: https://github.com/ximion/appstream/issues/195#issuecomment-462148814

**Comment by klali** [comment]
This is obviously complex.

We're not happy to have more complex licensing of the things in this repo, it's complex enough already. A copy of this file does exist in https://github.com/Yubico/libfido2/blob/master/udev/70-u2f.rules with a different licence though. Looking forwards a bit the future of libu2f-host is questionable, libfido2 will/should have the same functionality and more, so that might be a possible way forwards.

**Comment by nbraud** [comment]
@klali Thanks for the info; providing the U2F rules from `libfido2` might indeed be a better solution in the future.

Do you plan to eventually make the rules in `libfido2` authoritative?  As far as I understand, `libu2f-host` is currently authoritative (_i.e._ people submit change requests here and it's periodically copied to `libfido2`)
