### ISSUE TITLE
Windows.mk Compile Issues

### ISSUE THREAD

**Issue by donjuan201** [Yubico/libu2f-host#22]
Hi Guys, 

I am trying, and have for a while now, to compile the library to work in windows without any success. I manage to get the windows.mk file to compile up to the "cp ../$(PACKAGE)-$(VERSION).tar.xz ." (line 51) line after I removed all the $(HOST) entries from the file but I am stuck at resolving it from here on wards. NOTE: If I leave the $(HOST) entries in the file the json and hidapi build also fail with errors.

I installed a 32 and a 64 version of Debian running on VirtualBox just to complete the compile without any success :(

Can someone please assist. I have also tried to compile the tar.gz version with the same results.

The compiler complains that it can't find the ../$(PACKAGE)-$(VERSION).tar.xz file.

Please assist.

**Comment by klali** [comment]
a pre-requisite for the windows (and mac builds) is a dist file of the project, so if you run make dist you get such a file (and then execute make -f windows.mk 32bit VERSION=0.0.5

the windows make file is supposed to run with mingw-w64

if you want to get pre-compiled windows binaries you can get those at https://developers.yubico.com/libu2f-host/Releases/ instead of compiling yourself
